import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import { useState } from "react";

const headers = {
  origin: "https://resy.com",
  "accept-encoding": "gzip, deflate, br",
  "x-origin": "https://resy.com",
  "accept-language": "en-US,en;q=0.9",
  authorization: 'ResyAPI api_key="VbWk7s3L4KiK5fzlO7JD3Q5EYolJI7n5"',
  "content-type": "application/x-www-form-urlencoded",
  accept: "application/json, text/plain, */*",
  referer: "https://resy.com/",
  // "Content-Type": "application/json",
  authority: "api.resy.com",
  "user-agent":
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36",
};

async function login(email, password) {
  const formData = `email=${email}&password=${password}`;

  const response = await fetch("https://api.resy.com/3/auth/password", {
    method: "POST",
    headers: headers,
    body: formData,
  });

  const resData = await response.json();
  console.log(resData);
  const authToken = resData.token;
  const paymentMethodString = "{id:" + resData.payment_method_id + "}";
  console.log(authToken);
  return { authToken, paymentMethodString };
}

export default function Home() {
  const [loggedIn, setLoggedIn] = useState(false);
  const [authToken, setAuthToken] = useState("");
  const [paymentMethodString, setPaymentMethodString] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>get a fkn table tes tapp</div>
      <input
        type="text"
        value={email}
        onChange={(e) => setEmail(e.target.value)}
      ></input>
      <input
        type="text"
        value={password}
        onChange={(e) => setPassword(e.target.value)}
      ></input>
      <button
        onClick={async () => {
          const { authToken, paymentMethodString } = await login(
            email,
            password
          );
          setAuthToken(authToken);
          setPaymentMethodString(paymentMethodString);
        }}
      >
        Login
      </button>
      {authToken && <div>Logged in</div>}
    </div>
  );
}
